### ISSUE TITLE
Google map is empty

### ISSUE THREAD

**Issue by sylver-john** [Leadformance/widgets-client#5]
Hi, I'm developper from Razorfish and i use your widget. But i got some problems, steps by steps :
- i load your widget 
- i press the search button 
- it works, i got my results and the google map 
  But if
- i load your widget 
- i use the check-box to add a filter, i have to reload your widget ( the only way i found to add a filter after your widget was loaded. Or have you got a other solution ? )
- i press the search button
  => i got my results but the google map's div is empty

Could you help me please ? Thanks !

**Comment by GODDET** [comment]
Hi, 
For which client you want to use this widget ?
Regards,
